- Dockerfile
Bump alpine version to `3.10.3`
https://github.com/alpinelinux/docker-alpine/issues/34
> Bump alpine version to 3.10.3

- Dockerfile
- Makefile
- azure-pipelines.yml
- main.go
- version.go
- version_test.go
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/15
```
root@k8s-agentpool1-32372105-vmss000000:/etc/kubernetes/secrets-store-csi-providers/azure# ./provider-azure --version
{"version":"addversion1210","buildDate":"2019-12-10-22:24","minDriverVersion":"v0.0.7"}
```
> Add --version flag 

- Makefile
- azure-pipelines.yml
- Updates build command for windows binary
- Adds linux and windows build validation in azp
> update windows build command

- README.md
- pkg/azure/provider.go
- test/bats/tests/azure_v1alpha1_secretproviderclass.yaml
- test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
- test/bats/tests/user-assigned-identity/azure_v1alpha1_systemassignedidentityenabled.yaml
- test/bats/tests/user-assigned-identity/azure_v1alpha1_useridentityenabled.yaml
- test/bats/tests/user-assigned-identity/nginx-pod-user-identity-secrets-store-inline-volume-crd.yaml
In this PR:
- Add 2 new parameters (userAssignedIdentityID & useVMManagedIdentity) to support the integration with user assigned identity (AKS with MI enabled)
- Add tests
- Update Readme
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/30
> Add support for MSI 

- .pipelines/e2e-job-azure.yaml
- azure-pipelines.yml
- split into 2 different pipelines so we can manually trigger the azure pipeline
> split into two pipelines for manual trigger

- README.md
- examples/windows-pod-secrets-store-inline-volume-secret-providerclass.yaml
- Adds install commands and example for windows
> add docs for windows

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/69
> Add gh issue and PR template

- charts/csi-secrets-store-provider-azure/README.md
**What this PR does / why we need it**: Readme has incorrect link in `helm install`
Fixes #72 
> Fixed broken link for helm install

- README.md
- examples/nginx-pod-secrets-store-inline-volume-pod-identity.yaml
- examples/nginx-pod-secrets-store-inline-volume.yaml
- examples/pv-secrets-store-csi.yaml
- examples/v1alpha1_secretproviderclass.yaml
- examples/v1alpha1_secretproviderclass_podid.yaml
1. There is some missing pre-reqs, like configuring a key vault. Added a section/doc link.
1. Important data fields from Azure should be enumerated earlier in the doc, as its needed for swapping yaml out.
1. Added SP creation steps & env vars for setup on SP option
I'm did not get it working, as my pod is stuck in deployment - so do gut check me on the proposed changes.
> adding more commands to clarify steps / stages

- docs/pod-identity-mode.md
> docs: update doc for pod-identity mode

- README.md
- charts/csi-secrets-store-provider-azure/README.md
- docs/install-yamls.md
- docs/testing.md
> Add features to README

- Makefile
> bump version to 0.0.6

- README.md
- docs/getting-certs-and-keys.md
- sample/ingress-controller-tls/README.md
- Add note about using `objectType: secret` for tls
Fixes #104, Fixes #106 
> add note about using object type secret for tls

- charts/csi-secrets-store-provider-azure/README.md
- charts/csi-secrets-store-provider-azure/values.yaml
- Adds driver `logLevel.debug` as configurable value for driver dep
Fixes #124 
> add log debug configuration in helm chart

- test/bats/azure.bats
- test/bats/tests/pod-identity/azure_v1alpha1_podidentity.yaml
- test/bats/tests/pod-identity/nginx-pod-pi-secrets-store-inline-volume-crd.yaml
- test/bats/tests/pod-identity/pi_azure_identity_binding.yaml
- Adds e2e tests for `pod-identity` mode
Fixes #
> add e2e test for pod-identity mode

- Makefile
- Bump version to `0.0.7`
Fixes #
> bump version to 0.0.7

- Dockerfile
- windows.Dockerfile
> feat: remove periodic log from container

- charts/csi-secrets-store-provider-azure/README.md
- Adds helm chart, driver and key vault provider version matrix
Fixes #165 
> doc: add helm chart, driver, provider version matrix

- README.md
> doc: fix broken image link in readme

- .pipelines/e2e-job-azure.yaml
- .pipelines/e2e-tests-template.yaml
- .pipelines/templates/aks-engine-setup.yaml
- .pipelines/templates/aks-setup.yaml
- .pipelines/templates/build-images.yaml
- .pipelines/templates/teardown.yaml
- test/bats/azure.bats
- test/bats/tests/certificates/nginx-pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/nginx-pod-secrets-store-inline-volume-crd.yaml
- test/bats/tests/pod-identity/nginx-pod-pi-secrets-store-inline-volume-crd.yaml
- test/bats/tests/user-assigned-identity/nginx-pod-user-identity-secrets-store-inline-volume-crd.yaml
> test: add pipeline for aks cluster

- README.md
- deployment/pod-security-policy.yaml
- Adds sample PSP required for driver and provider with minimum scope
Fixes #180 
> doc: add example psp and note in readme

- README.md
- docs/pod-identity-mode.md
- docs/service-principal-mode.md
- examples/nginx-pod-inline-volume-pod-identity.yaml
- examples/nginx-pod-inline-volume-service-principal.yaml
- examples/nginx-pod-inline-volume-system-assigned-identity.yaml
- examples/nginx-pod-inline-volume-user-assigned-identity.yaml
- examples/v1alpha1_secretproviderclass_pod_identity.yaml
- examples/v1alpha1_secretproviderclass_service_principal.yaml
- examples/v1alpha1_secretproviderclass_system_assigned_identity.yaml
- examples/v1alpha1_secretproviderclass_user_assigned_identity.yaml
- Adds examples for `SecretProviderClass` and pod definitions for each auth mode supported
- Adds build badges to readme 
Fixes #179, fixes #161 
> docs: add examples and build badges

- Dockerfile
- Makefile
- windows.Dockerfile
> chore: bump version to 0.0.8

- examples/nginx-pod-secrets-store-deployment-pvc.yaml
- examples/nginx-pod-secrets-store-pvc.yaml
> chore: update example manifest for pvc

- Dockerfile
fixes #221 
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? **no**
> chore: update debian base image to v2.1.3

- .pipelines/e2e-tests-template.yaml
- .pipelines/load-tests-template.yaml
- .pipelines/nightly.yaml
- .pipelines/templates/aks-engine-setup.yaml
- .pipelines/templates/aks-setup.yaml
- .pipelines/templates/assign-user-identity.yaml
- .pipelines/templates/build-images.yaml
- .pipelines/templates/cleanup-images.yaml
- .pipelines/templates/publish-load-test-result.yaml
- .pipelines/templates/teardown.yaml
- Makefile
- azure-pipelines.yml
- test/load/config-deployment-template.yaml
- test/load/deployment-template.yaml
- test/load/secret-provider-class-template.yaml
- Updates the current CI pipeline to use templates
- Adds lint as part of CI
> add load test pipeline to nightly job

- .pipelines/templates/teardown.yaml
- update password variable to `AAD_CLIENT_SECRET`.
> fix: update client secret variable in teardown

- pkg/provider/provider.go
- pkg/provider/provider_test.go
- `TrimSpace` all the mount parameters
fixes #197 
> fix: add trimspace to sanitize yaml fields

- README.md
> Update link for rotation doc

- .gitignore
- Makefile
- Update deps for helm lint
- Enable helm lint for `manifest_staging`
> chore: helm dep update for lint + lint manifest_staging

- Makefile
Bumps provider version to `0.0.10` for next release
> chore: bump version to 0.0.10

- .github/workflows/gh-pages.yaml
- .gitignore
- docs/ingress-tls.md
- netlify.toml
- website/content/en/configurations/identity-access-modes/pod-identity-mode.md
- website/content/en/configurations/identity-access-modes/service-principal-mode.md
- website/content/en/configurations/sync-with-k8-secretes.md
- website/content/en/demos-and-tutorials/tutorials/setup-keyvault.md
- website/content/en/getting-started/_index.md
- website/content/en/testing/_index.md
- website/content/en/troubleshooting/equal-to-and-greater-than-version-0.0.9.md
- website/content/en/troubleshooting/less-than-version-0.0.9.md
- website/content/en/upgrading/_index.md
- website/layouts/_default/baseof.html
- website/layouts/_default/content.html
- website/layouts/_default/list.html
- website/layouts/_default/list.rss.xml
- website/layouts/_default/search.html
- website/layouts/_default/single.html
- website/layouts/home.html
- website/layouts/partials/section-index.html
- website/layouts/partials/sidebar-tree.html
- Adds netlify config for static site
fixes #319 
partially resolves #256 
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? **Yes**
- The website layouts are from https://github.com/LisaFC/justdocs
> docs: add plumbing for static site

- Makefile
> chore: bump version to 0.0.11

- docs/ingress-tls.md
> docs: fix indentation in ingress doc

- Dockerfile
Temporary fixes for CVE's until there is an official image
partial fix for #354 
> fix: CVE-2020-27350, CVE-2020-29362

- .github/PULL_REQUEST_TEMPLATE.md
This is a follow up PR to https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/419
> chore: update github pr template

- .gitignore
- Makefile
- README.md
- azure-pipelines.yml
- codecov.yml
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/359
> ci: add code coverage as part of CI

- go.mod
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/provider/provider.go
- pkg/provider/provider_test.go
> test: add unit tests for auth and provider pkgs

- website/content/en/getting-started/installation/_index.md
> docs: fix typo in installation steps

- .github/ISSUE_TEMPLATE/bug-report.md
> chore: add troubleshooting guide url in issue template

- Dockerfile
> fix: CVE-2021-24032

- website/content/en/configurations/enable-auto-rotation-secrets.md
- website/content/en/configurations/sync-with-k8-secretes.md
- website/content/en/getting-started/installation/_index.md
- website/content/en/upgrading/_index.md
fixes https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/474
> docs: fix rotation url

- website/content/en/demos/standard-walkthrough/_index.md
> docs: fix parameter in walkthrough

- azure-pipelines.yml
upload token is not required: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token
- remove `CODECOV_TOKEN` env var as it's not required: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token
> ci: remove CODECOV_TOKEN env var

- manifest_staging/deployment/pod-security-policy.yaml
Update pod security policies to reflect latest required spec
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/479
> fix: updates psp to match helm chart

- website/content/en/configurations/deploy-in-openshift.md
- website/content/en/getting-started/installation/_index.md
> docs: add installation steps for Azure RedHat Openshift

- website/content/en/getting-started/usage/_index.md
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/523
> fix: update url reference in usage doc

- Makefile
> chore: bump version to 0.0.16

- test/e2e/secret_test.go
This PR adds e2e test for k8s sync secrets of type `tls` and `opaque`.
fixes: #107 
> feat: adds e2e test for k8s secret sync

- manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml
> helm: fix security context privileged for linux

- .pipelines/templates/e2e-test-kind.yaml
- Makefile
> chore: update kind version to v0.11.0

- manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml
`allowPrivilegeEscalation: false` cannot be set when `privileged: true`
> helm: fix security context for linux

- Makefile
> chore: bump version to v0.2.0

- .pipelines/templates/cleanup-images.yaml
- Refactor cleanup image template and include arm64 image cleanup
> ci: refactor cleanup image template

- README.md
> chore: update build status badge to new pipeline

- website/content/en/configurations/identity-access-modes/_index.md
- website/content/en/configurations/identity-access-modes/pod-identity-mode.md
- website/content/en/configurations/identity-access-modes/service-principal-mode.md
- website/content/en/configurations/identity-access-modes/system-assigned-msi-mode.md
- website/content/en/configurations/identity-access-modes/user-assigned-msi-mode.md
This PR adds guidance for access options.
fixes: #235 
> docs: adds pros n cons for access methods

- hack/cherry_pick_pull.sh
Adds a script for cherry pick to make it easier for cherry picks to release branches.
This script is taken as is from https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh
All credits to contributors.
> chore: add cherry_pick_pull script from kubernetes

- test/e2e/Makefile
- test/e2e/auto_rotation_test.go
- test/e2e/certificates_test.go
- test/e2e/cleanup.go
- test/e2e/custom_cloudenv_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/framework/cluster_proxy.go
- test/e2e/framework/deploy/deploy.go
- test/e2e/framework/exec/kubectl.go
- test/e2e/framework/helm/helm.go
- test/e2e/framework/interfaces.go
- test/e2e/framework/keyvault/keyvault.go
- test/e2e/framework/namespace/namespace.go
- test/e2e/framework/openssl/openssl.go
- test/e2e/framework/pod/pod.go
- test/e2e/framework/scheme.go
- test/e2e/framework/secret/secret.go
- test/e2e/framework/secretproviderclass/secretproviderclass.go
- test/e2e/framework/timeout.go
- test/e2e/key_test.go
- test/e2e/pod_identity_test.go
- test/e2e/secret_test.go
- test/e2e/user_assigned_identity_test.go
- tools/tools.go
- Updates driver version for deployment manifest tests to `v1.0.0-rc.0`
- Run `gofmt` to update build tags in `test/e2e`
- Remove `GODEBUG=x509ignoreCN=0` as it's removed in go 1.17
> test: update driver version to v1.0.0-rc.0 and run gofmt

- .github/workflows/markdown-link-check.yaml
- docs/remote-devcontainer.md
- examples/kind/README.md
- website/README.md
- website/content/en/configurations/identity-access-modes/_index.md
- website/content/en/configurations/ingress-tls.md
- website/content/en/demos/standard-walkthrough/_index.md
- website/content/en/getting-started/installation/_index.md
- website/content/en/getting-started/usage/_index.md
- website/content/en/upgrading/_index.md
- Adds workflow for checking dead links in docs
- This will run as part of pull requests (non-blocking), periodically everyday and on push to the master branch.
> ci: add markdown-link-check workflow

- .pipelines/templates/e2e-test-kind.yaml
> test: add kubernetes v1.23.0 kind cluster

- Makefile
- pkg/auth/auth.go
- pkg/provider/provider.go
Cherry pick of #730 on release-1.0.
#730: update klog.InfoS to klog.V(5).InfoS
> Automated cherry pick of #730: update klog.InfoS to klog.V(5).InfoS

- .pipelines/templates/unit-test.yaml
- Makefile
> ci: enable shellcheck

- charts/index.html
Adds `index.html` to gh-pages charts repository. Render in my fork: https://aramase.github.io/secrets-store-csi-driver-provider-azure/charts/
> chore: add index.html

- .github/ISSUE_TEMPLATE/bug-report.md
ref https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/892
> chore: fix troubleshooting link in issue template

- website/content/en/configurations/deploy-in-openshift.md
- website/content/en/configurations/feature-flags.md
- website/content/en/configurations/identity-access-modes/service-principal-mode.md
command ref: https://www.mankier.com/1/oc-adm-policy-remove-scc-from-user
fixes #910 
> docs: fix uninstall commands in openshift

- website/content/en/_index.md
- Updates supported releases in the doc
> docs: update supported releases - v1.2.x and v1.1.x

- go.mod
- go.sum
- test/e2e/go.mod
- test/e2e/go.sum
ref: https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=50041&view=logs&j=50e5c204-a982-5a63-4824-cf22f1b24a4e&t=795dd060-7255-5745-ea64-907869e3f465&s=96ac2280-8cb4-5df5-99de-dd2da759617d
> security: fix CVE-2022-27191

- arc/portal_gallery_package/Manifest.json
> chore: updates gallery pkg version

- manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
> chore: updates prom mdm converter image

- .pipelines/templates/aks-setup.yaml
Resolves https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=53327&view=logs&j=e17763bf-6a27-598e-668f-b70e15d07d94&t=8c973a37-001c-5b1c-a9ca-be4e851b7fe2
> ci: pin aks-preview version to `0.5.87`

- charts/artifacthub-repo.yml
Adds metadata file to add Verified Publisher label on Artifact Hub.
https://artifacthub.io/packages/helm/csi-secrets-store-provider-azure/csi-secrets-store-provider-azure
> chore: adds artifact hub metadata file

- website/content/en/configurations/identity-access-modes/workload-identity-mode.md
> docs: use azure cli for setting up federated identities

- website/content/en/configurations/identity-access-modes/_index.md
- website/content/en/configurations/identity-access-modes/workload-identity-mode.md
- Add steps for configuring workload identity with managed identity
> docs: add workload identity steps for managed identity

- website/content/en/_index.md
> docs: update supported releases - v1.3.x and v1.4.x

- website/content/en/demos/community-demos-and-presentations/houssem-dellai-workload-identity.md
I added a new community demo : video demo that uses Workload Identity.
> docs: add video demo for workload identity + AKV

- charts/csi-secrets-store-provider-azure/Chart.lock
- charts/csi-secrets-store-provider-azure/Chart.yaml
- charts/csi-secrets-store-provider-azure/README.md
- charts/csi-secrets-store-provider-azure/arc-values.yaml
- charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
- charts/csi-secrets-store-provider-azure/values.yaml
- docs/Release_Management.md
- manifest_staging/charts/csi-secrets-store-provider-azure/Chart.lock
- manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml
- manifest_staging/charts/csi-secrets-store-provider-azure/README.md
- manifest_staging/charts/csi-secrets-store-provider-azure/arc-values.yaml
- manifest_staging/charts/csi-secrets-store-provider-azure/values.yaml
- test/e2e/framework/deploy/deploy.go
> release: update manifest and helm charts for v1.4.1

- .pipelines/e2e-job-azure.yaml
- .pipelines/nightly.yaml
- azure-pipelines.yml
- switch to using mariner pool for PR and nightly jobs
> ci: switch to using mariner pool

- .github/semantic.yml
- make semantic check title only
> ci: make semantic check title only

- manifest_staging/charts/csi-secrets-store-provider-azure/config/gcstenant-conf.json
- manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
This PR updates logging agent for Azure Arc.
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1363
> chore: updates amacoreagent for Arc

- charts/csi-secrets-store-provider-azure/Chart.yaml
- charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
- manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml
> fix: `v1.5.1` helm chart release to fix fluentd config env var name

- Dockerfile
> chore: use base images from mcr

- manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
This PR upgrades the `MSI adapter` used in Arc extension.
> fix: updates MSI adapter

- charts/csi-secrets-store-provider-azure/Chart.yaml
- charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
- manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml
> fix: v1.5.2 helm chart release to upgrade msi-adapter image

- .pipelines/templates/e2e-test-kind.yaml
- overwrite pool images using demands
> ci: overwrite pool images using demands

- .pipelines/templates/scan-images.yaml
Removing this image from scan. We will revisit the usage of this image later and enable the scan if we plan to actively maintain it.
Fixes #1542 
> chore: removes conformance image from scan

- manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
> chore: bumps monitoring images

- manifest_staging/charts/csi-secrets-store-provider-azure/arc-values.yaml
- manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
> feat: turning off Arc ext monitoring by default

- .github/workflows/create-release.yaml
- .goreleaser.yml
Fixing - https://github.com/Azure/secrets-store-csi-driver-provider-azure/actions/runs/9684012172/job/26720779814
> ci: updates goreleaser

- .goreleaser.yml
```bash
➜ goreleaser check        
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
> ci: skip builds goreleaser config

- docs/sample/ingress-controller-tls/readme.md
Change to an accessible URL.
Updated the documentation
No.
> docs: fix broken link in ingress controller sample

- pkg/auth/auth.go
Cherry pick of #1730 on release-1.6.
#1730: chore: update sp credential mode logging
> chore: update sp credential mode logging

- CODEOWNERS
Thank you for all the contributions you have made to the project, @nilekhc!
> ci: add @enj, remove @nilekhc from CODEOWNERS
