README.md, azure-pipelines.yml, test/bats/azure.bats
- Update driver references to `kubernetes-sigs`
- Update provider installation step for e2e tests as provider charts have now been removed
=> update e2e tests and driver repo

README.md, examples/nginx-pod-secrets-store-inline-volume-pod-identity.yaml, examples/nginx-pod-secrets-store-inline-volume-secretproviderclass-podid.yaml, examples/nginx-pod-secrets-store-inline-volume-secretproviderclass.yaml, examples/nginx-pod-secrets-store-inline-volume.yaml, examples/pv-secrets-store-csi.yaml, test/bats/tests/nginx-pod-secrets-store-inline-volume-crd.yaml, test/bats/tests/nginx-pod-secrets-store-inline-volume.yaml
- Driver version `v0.0.8` has been released with the driver name changes. Updating all the examples and tests to reflect the new driver name.
=> update driver name in examples and tests

pkg/azure/provider.go
Since https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/31 is merged, `GetManagementToken` is no longer required.
=> remove GetManagementToken unused code

Makefile, azure-pipelines.yml, test/bats/azure.bats
Fixes #40 
Currently, with Helm 3 if you want to assign the installed chart to a specific namespace that doesn't exist, you must externally create that namespace (kubectl).  https://github.com/helm/helm/issues/6794
=> Upgrade to Helm 3 for E2E Tests 

README.md
With the new release of pod-identity 1.6, the client-go version is case sensitive. So this PR updates the docs to reflect the correct cases for the ` AzureIdentity` and `AzureIdentityBinding` resources.
=> update docs for pod-identity

pkg/azure/provider.go
Currently cert data returned from key vault is the raw data, not in the format we would expect it to be. This PR returns the cert in pem or pfx format.
=> Fix cert value generation

Makefile
- Bump `IMAGE_VERSION` to 0.0.5 in prep for the next release.
=> bump version to 0.0.5

pkg/azure/provider.go
Currently, only RSA modulus is supported. The code panics for other key types. We should check the type of the key before returning.
Fixes #
=> check key type before return

charts/csi-secrets-store-provider-azure/templates/provider-azure-installer-windows.yaml, charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml, charts/csi-secrets-store-provider-azure/values.yaml
Adding node selector capability to be able to pick a system mode node pool
No existing issue
Grabbed node selector format from [AAD Pod identity project](https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity)
=> Adding node selector Values to chart

pkg/azure/provider.go, pkg/version/version.go
Adds `csi-secrets-store/"Version"` user agent to key vault client and ADAL calls
Fixes #91 
=> add user agent with version number

.github/ISSUE_TEMPLATE/bug-report.md
Adds `kubectl get nodes -o wide` to issue template as `kubectl version` only provides the server version.
Fixes #
=> add kubectl node version to issue template

charts/csi-secrets-store-provider-azure/README.md, charts/csi-secrets-store-provider-azure/templates/provider-azure-installer-windows.yaml, charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml, charts/csi-secrets-store-provider-azure/values.yaml, deployment/provider-azure-installer-windows.yaml, deployment/provider-azure-installer.yaml
- Update `nodeSelector` to `kubernetes.io/os` as `beta.kubernetes.io/os` will be deprecated in 1.19
Fixes #
=> update node selector to kubernetes.io/os

cmd/main.go, pkg/azure/provider.go
- Sets context timeout to 1m50s for access to kv. This ensures the request is terminated and error is returned when time to access kv takes > 2m. The default volume timeout for kubelet is 2m3s and this change honors the value. If the context in provider is not set, then the driver will terminate the process based on the context, but the error from provider will not be surfaced to the user. 
Sample error when network policies deny outbound traffic in cluster - 
```
time="2020-07-09T19:07:35Z" level=info msg="time=\"2020-07-09T18:57:35Z\" level=info msg=\"using pod identity to access keyvault\"\ntime=\"2020-07-09T18:57:35Z\" level=info msg=\"mounting secrets store object content for kube-system/nginx-secrets-store-env-var\"\ntime=\"2020-07-09T18:57:35Z …
```
=> chore: set context timeout for access to kv

README.md, pkg/azure/provider.go, pkg/azure/provider_test.go
If `cloudEnvFileName ` is defined, then provider can set the [AZURE_ENVIRONMENT_FILEPATH](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L28) env var. The SDK should then be able to [read](https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L224-L226) from the file which is already on host for `AzureStackCloud`. 
Fixes #144 
=> feat: allow defining a custom azure environment

README.md
There are two links to example files in [kubernetes-sigs/secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) which got moved to a new subdirectory. 
Fixes #
Didn't see any open issues about this.
This documentation has been amazingly helpful, thank you! 😄
=> Fix links to example files that were moved.

pkg/azure/provider.go, pkg/azure/provider_test.go
For custom clouds, the cloud name will be set to `custom`. If `p.AzureCloudEnvironment.Name` is used to ParseAzureEnvironment the second time, it'll result in cloud name `custom` not found error. 
Fixes #
=> fix: update kv endpoint suffix for custom cloud

Makefile, README.md, azure-pipelines.yml, docs/custom-environments.md, pkg/azure/provider.go, pkg/azure/provider_test.go, test/bats/azure.bats, test/bats/tests/azure_v1alpha1_secretproviderclass.yaml, test/custom_environment.json, test/e2e/cluster_configs/linux-custom-cloud.json, test/kind-config.yaml
Provider fails with error `cloudName is not valid` if `cloudName: "AzureStackCloud"`.
Flipping the execution order of functions `setAzureEnvironmentFilePath` and `ParseAzureEnvironment` solves the problem.
I noticed that the custom cloud scenario is not covered by the e2e suite so I added a few extra modifications to add coverage at least if running locally.
Marked as `work-in-progress` because there a few things we could possibly add to this PR (or a subsequent one):
1. Custom cloud coverage in CI pipeline
1. Document minimum required `environment.json`
1. Add extra mount to `provider-azure-installer.yaml` for the custom environment file 
Please let me know how you want to scope this PR.
Related to #153
**Please answer the …
=> fix: custom azure environment not supported

README.md
The doc hasn't updated during renaming the file in https://github.com/Azure/secrets-store-csi-driver-provider-azure/commit/a4da7f93d13f67e6625d858eb4816496787eeecd#diff-f8e840de9d1a8ad74c96e6e08a892b45
~~- [ ] added unit tests and e2e tests (if applicable).~~
n/a
- no (Not contain code from nor inspired by another project)
=> Fix missing link in README.md

manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/README.md, manifest_staging/charts/csi-secrets-store-provider-azure/requirements.lock, manifest_staging/charts/csi-secrets-store-provider-azure/requirements.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/templates/_helpers.tpl, manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer-windows.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/templates/serviceaccount.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/values.yaml, manifest_staging/deployment/pod-security-policy.yaml, manifest_staging/deployment/provider-azure-installer-windows.yaml, manifest_staging/deployment/provider-azure-installer.yaml, test/bats/azure.bats
- Adds a new `manifest_staging` dir to hold the latest helm charts and deployment manifests. These manifests are moved over to the official `deployment` and `charts` dir at the time of the release. 
=> chore: add manifest staging dir to hold new manifests

Makefile
- Bumps version to `0.0.9` preparing for next release
depends on #246 to be merged first
=> chore: bump version to 0.0.9

README.md, docs/how-to-upgrade.md, docs/install-yamls.md
The upcoming release `0.0.9` for Azure Key Vault Provider is incompatible with Secrets Store CSI Driver versions < `v0.0.14`.
- The driver is packaged as dependency in the provider helm charts and users running `helm upgrade` from the charts repo don't require any manual actions.
- The doc details steps users need to take for manual upgrade scenario
=> docs: add upgrade doc for 0.0.9

pkg/provider/provider.go, pkg/provider/provider_test.go
- Add validation for file name
Yes
Implementation based on reference from:
- [validateLocalDescendingPath] https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L1158-L1170
- [validatePathNoBacksteps] https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L1172-L1186
=> feat: add validation for file name

docs/pod-identity-mode.md
The linked README does not exist and I could not see any equivalent, so removing the dead documentation.
=> docs: Update link to README for pod identity

Makefile, cmd/main.go, pkg/version/version.go
Enables profiling using pprof and also logs the current AKV provider
version at startup.
- Adds pprof profiling
- Adds logs for current AKV provider version during startup
- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? **No**
=> feat: add pprof profiling

Makefile
This is a workaround until the bug is fixed in buildkit: https://github.com/moby/buildkit/pull/1879
=> fix: windows image build with buildx

cmd/main.go, go.mod, test/bats/azure.bats
- Switches to using `flag` instead of `pflag`
fixes #330 
=> fix: switch to using flag instead of pflag

.pipelines/e2e-tests-template.yaml, .pipelines/load-tests-template.yaml, .pipelines/templates/build-images.yaml, .pipelines/templates/cleanup-images.yaml, .pipelines/templates/get-logs.yaml, .pipelines/templates/scan-images.yaml, Dockerfile, Makefile, azure-pipelines.yml, cmd/main.go, docs/testing.md, test/bats/azure.bats, website/content/en/testing/_index.md, windows.Dockerfile
- Adds image scan as part of CI
- Refactors `Makefile`
- Adds target for windows multi-arch image builds
- Adds log collection as part of CI to enable debugging
fixes #311 
fixes #255
=> feat: add image scanning and refactor Makefile

Dockerfile, cmd/main.go, manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml, manifest_staging/deployment/provider-azure-installer.yaml, pkg/server/server.go
- Adds grpc health probe for linux daemonset
fixes #310 
=> feat: add grpc health probe for linux daemonset

README.md
This is a simple comment that emphasizes that syncing is not the primary functionality of this driver as clearly said [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/230#issuecomment-691278833).
Just costed us some time to realize that, so I think it makes sense to have it directly in the documentation.
=> Add a note on when secrets are actually synced

Dockerfile
=> chore: update debian-base image to buster-v1.3.0

.pipelines/e2e-tests-template.yaml, .pipelines/nightly.yaml, .pipelines/soak-tests-template.yaml
=> ci: add soak tests with aks clusters

website/content/en/configurations/identity-access-modes/system-assigned-msi-mode.md, website/content/en/configurations/identity-access-modes/user-assigned-msi-mode.md, website/content/en/demos/standard-walkthrough/_index.md
- Update system-assigned managed identity mode doc
- The system-assigned managed identity created by AKS is not part of the node VM/VMSS. This means users can create their own system-assigned managed identity and use to access keyvault. Also, pinged @miwithro to update the AKS docs to say the same when creating a cluster with managed identity. Even though the cluster identity profile shows `type: SystemAssignedIdentity`, there is no system-assigned managed identity in the VM/VMSS.
fixes #388 
fixes #389 
**Special Notes for …
=> docs: clarify usage in system-assigned mode

charts/index.yaml
The short format of scheme is not available for _Helm depencendies update_ command
The `//` break the donwload link :
```
helm dependency update myHelmChart/
Getting updates for unmanaged Helm repositories...
[...]
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading csi-secrets-store-provider-azure from repo https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts/
Save error occurred:  could not download https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts/raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts/csi-secrets-store-provider-azure-0.0.17.tgz: failed to fetch https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/ …
```
=> fix: use scheme long format for Helm dependencies

windows.Dockerfile
`mcr.microsoft.com/powershell:lts-nanoserver` was required before as the provider binary need to be installed but is no longer required. Switching to use `mcr.microsoft.com/windows/nanoserver` instead.  
=> chore: use nanoserver base image for windows

.pipelines/e2e-tests-template.yaml, .pipelines/nightly.yaml, .pipelines/templates/aks-engine-setup.yaml, .pipelines/templates/aks-setup.yaml, .pipelines/templates/aks-upgrade.yaml, test/e2e/e2e_suite_test.go, test/e2e/framework/config.go, test/e2e/framework/exec/kubectl.go, test/e2e/framework/helm/helm.go
- Adds cluster upgrade test as part of CI nightly runs for AKS
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/174
=> ci: add cluster upgrade test

Dockerfile
- updates debian base image to `debian-base-amd64:buster-v1.5.0`
=> chore: update debian base to buster-v1.5.0

pkg/server/server.go, pkg/server/server_test.go
- Sends version response back to the driver
=> feat: add version response for provider

website/content/en/configurations/sync-with-k8-secretes.md
- Adds clarification about the sync k8s secret namespace
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/241
=> docs: clarify sync k8s secret namespace

examples/sync-as-kubernetes-secret/dockerconfigjson_synck8s_v1alpha1_secretproviderclass.yaml, examples/sync-as-kubernetes-secret/tls_synck8s_v1alpha1_secretproviderclass.yaml, website/content/en/configurations/sync-with-k8-secretes.md
- Adds example for syncing `dockerconfigjson` as Kubernetes secrets
- Updates example references in the docs
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/450
=> docs: add example for sync k8s secret dockerconfigjson

pkg/provider/provider.go, test/e2e/framework/secretproviderclass/secretproviderclass.go, test/e2e/key_test.go
- Adds support for `RSA-HSM` and `EC-HSM` keys
fixes #469 
=> feat: add support for RSA-HSM and EC-HSM keys

test/e2e/framework/scheme.go
=> test: use AddToScheme for the csi-secrets-store apis

Dockerfile, manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml, manifest_staging/deployment/provider-azure-installer.yaml
Switches to using distroless static `nonroot` base image for Linux images. As root permissions are required for binding the socket, `runAsUser: 0` is set in the securityContext.
fixes #516 
=> feat: use distroless base image

deployment/pod-security-policy.yaml, manifest_staging/deployment/pod-security-policy.yaml
**Reason for Change**: [error]error: error validating "https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/pod-security-policy.yaml": error validating data: ValidationError(PodSecurityPolicy.spec): unknown field "hostPort" in io.k8s.api.policy.v1beta1.PodSecurityPolicySpec; if you choose to ignore these errors, turn validation off with --validate=false
**Does this change contain code from or inspired by another project?** No 
=> Update pod-security-policy.yaml to correct the unknown feild "hostPort"

.pipelines/nightly.yaml, azure-pipelines.yml
- Adds unit tests as part of nightly runs so we can get image scan results
- Adds kind tests as part of nightly to test driver write secret feature periodically
=> chore: add unit tests and kind tests as part of nightly

.pipelines/templates/e2e-test-kind.yaml
=> ci: use variable group for kind e2e jobs

deployment/pod-security-policy.yaml
When we try to apply this file with kubectl apply it shows some formatting errors, this fixes them.
=> Update pod-security-policy.yaml remove formatting issues

Dockerfile, Makefile, windows.Dockerfile
- Adds arm64 build
Fixes #501 
=> feat: add arm64 build

pkg/provider/provider.go
- Checks if secret/key/cert is not nil before dereferencing to get value and ID.
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/532
=> fix: check if result bundle not nil before dereferencing

website/content/en/configurations/identity-access-modes/service-principal-mode.md, website/content/en/getting-started/usage/_index.md
My team just wasted a week fighting to get User-assigned Managed Identity to work for on-premises kubernetes cluster, including open a support ticket with Azure, which bounced from the Azure Key Vault team to the Identity and Access Management team.  After seeing @nilekhc's comment in issue #514, we discovered that Service Principal is the only option for us.  We could have saved a lot of time if the documentation we were following made it clear that for non Azure environments such as ours, Service Principal was our only option.
none
=> Add clarity about Service Principal being the only Identity Access Mode allowed for non Azure environments

.pipelines/templates/load-test.yaml
- Adds `secrets-store-csi-driver.syncSecret.enabled=true` for helm install in load test pipeline.
=> fix: add syncSecret.enabled=true in helm install for load test

website/content/en/configurations/set-env-var.md, website/content/en/configurations/sync-with-k8s-secrets.md, website/content/en/troubleshooting/_index.md
- Adds a note about setting `syncSecret.enabled=true` for using sync secret feature.
- Adds to troubleshooting guide.
=> docs: add note for `syncSecret.enabled=true`

manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml, manifest_staging/deployment/provider-azure-installer.yaml
This PR adds following additional security context.
1. `allowPrivilegeEscalation: false`
2. `readOnlyRootFilesystem: true`
fixes #537 
=> chore: set allowPrivilegeEscalation to false

pkg/auth/auth.go
Logs the response which contains error with pod identity.
Example:
```bash
E0623 17:59:23.823541       1 server.go:55] "failed to process mount request" err="failed to get keyvault client: failed to get key vault token: nmi response failed with status code: 404, err: getting assigned identities for pod default/nginx-b64f4d687-jnppl in CREATED state failed after 1 attempts, retry duration [2]s, error: <nil>. Check MIC pod logs for identity assignment errors\n"
```
=> chore: log pod identity response for error

website/content/en/configurations/sync-with-k8s-secrets.md, website/content/en/troubleshooting/_index.md, website/content/en/upgrading/_index.md
- Explicitly set `secrets-store-csi-driver.syncSecret.enabled=true` in the docs.
fixes #553 
=> docs: set secrets-store-csi-driver.syncSecret.enabled for sync secret

website/content/en/configurations/identity-access-modes/service-principal-mode.md
Adds explanation for the `nodePublishSecretRef` namespace limitation.
fixes #531 
=> docs: add nodepublishsecretref namespace limitation

docs/Release_Management.md
This PR adds release management process doc.
Fixes: #507 
=> docs: adds release management doc

website/content/en/troubleshooting/_index.md
This PR adds sample commands to test AKV connectivity from pod running on host network.
fixes: #552 
=> docs: adds sample cmds to test AKV connectivity

website/content/en/configurations/sync-with-k8s-secrets.md
Adds note about the lifetime of the synced Kubernetes secret tied to the pods consuming it.
fixes #321 
=> docs: add note about the lifetime of synced k8s secrets

manifest_staging/charts/csi-secrets-store-provider-azure/Chart.lock, manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/requirements.lock
In helm3 the `requirements.yaml` has been consolidated into `Chart.yaml`: https://helm.sh/docs/faq/changes_since_helm2/#consolidation-of-requirementsyaml-into-chartyaml
=> helm: move helm dependencies to Chart.yaml

.pipelines/templates/e2e-test-kind.yaml, azure-pipelines.yml, cmd/main.go, pkg/provider/provider.go, test/e2e/framework/config.go, test/e2e/framework/helm/helm.go
Driver write secrets feature has been enabled by default in `v0.1.0` release. This PR makes the flag configuration no-op to not allow disabling the feature. The flag will be removed altogether from code, deployment and helm charts in n+2 releases.
=> chore: make `--driver-write-secrets` flag no-op

.pipelines/templates/aks-setup.yaml
This PR adds `containerd` as default containerRuntime in params.
=> chore: adds default runtime

cmd/main.go, pkg/provider/provider.go, pkg/provider/provider_test.go, pkg/version/version.go
Keyvault name is per `SecretProviderClass`. So switching to just getting the vault URL and kv client once instead of recreating the client for every single object in the array.
=> refactor: create kv client once and update to structured logging

pkg/auth/auth_test.go, pkg/provider/provider_test.go
Because of changes in https://github.com/Azure/go-autorest/pull/613, the tests that depends on `adal.NewServicePrincipalTokenFromMSI` will fail as it requires the IMDS endpoints be available. There is currently no option to pass a custom msi endpoint to mimic the behavior. So this PR deletes the two test cases that depend on the function. 
The unit tests are not failing in the CI because the agents we're running the tests on are Azure VMs. So they have the IMDS endpoint.
=> chore: cleanup unit tests that have external dependency

cmd/main.go, pkg/metrics/exporter.go, pkg/server/healthz.go
- Updating `Fatalf` to `ErrorS` for switch to structured logging.  Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
=> chore: use ErrorS instead of Fatalf for structured logging

.github/workflows/cover.yaml, .pipelines/templates/unit-test.yaml
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/647
=> chore: replace deprecated codecov uploader with GitHub action

.pipelines/templates/e2e-test-azure.yaml
The Kubernetes cluster upgrade in nightly runs have taken a while which
causes the pipeline to timeout in 90m. Bumping it to 120m based on some
of the earlier test results to provide more time for pipeline to
complete.
Ref nightly run: https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=27623&view=results
=> ci: bump test timeout to 120m

website/content/en/configurations/custom-environments.md
`/etc/ssl/certs` are required in custom cloud environments to be able to communicate with the custom keyvault endpoint.
=> docs: add `/etc/ssl/certs` volume mount for custom cloud

Makefile
Cherry pick of #660 on release-1.0.
#660: feat: adds windows server 2022
=> Automated cherry pick of #660: feat: adds windows server 2022

.pipelines/templates/e2e-test-kind.yaml, Dockerfile, Makefile, windows.Dockerfile
- Updates default kubernetes version to `v1.22.2`
- Make docker buildx builder name customizable
- Use `TARGETARCH` instead of `ARCH` in dockerfile
=> chore: use kubernetes 1.22.2 for test and update makefile

.pipelines/templates/e2e-test-kind.yaml, Makefile
- Bumps to kubernetes version `v1.22.4` for 1.22
- 1.19 is EOL, so removing 1.19 tests
=> test: bump kubernetes version to v1.22.4 and remove v1.19

pkg/provider/provider.go, pkg/provider/provider_test.go, pkg/server/server_test.go
The YAML for secret provider class can be created by a template engine and all the objects listed there can depend on a template variable to be truthy. In this case, when all of them are falsy, it becomes a special case if empty objects array is not allowed. Example:
```
objects: |
array:
{{ if condition1 }}
- |
objectName: "Secret1"
objectType: secret
objectFormat: pfx
objectEncoding: base64
{{ end }}
{{ if condition2 }}
- |
objectName: "Secret2"
objectType: secret
objectFormat: pfx
objectEncoding: base64
{{ end }}
```
If `condition1` and `condition2` are both falsy, the provider returns an error, but simply mounting an empty volume would be more consistent and it doesn't require special handling.
**Does this change contain code …
=> feat: allow empty objects array 

test/e2e/go.mod, test/e2e/go.sum
Fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/security/dependabot/test/e2e/go.sum/github.com%2Fopencontainers%2Frunc/open by upgrading runc to `v1.0.3`
=> security: fix CVE-2021-43784

Makefile, pkg/auth/auth.go, pkg/provider/provider.go
- Update `klog.InfoS` to `klog.V(5).InfoS`
- Update makefile target `make image` as it's no longer available to `$(MAKE) container-all push-manifest`
**Issue Fixed**: #649 
=> fix: klog verbose update

go.mod, go.sum, test/e2e/go.mod, test/e2e/go.sum
- Bumping the adal deps to `v0.9.18` that contains fix for the aggressive health checks in the prior versions.
- IMDS health check has been removed from every token request call and instead moved to the Get authorizer. Reference issue: https://github.com/Azure/go-autorest/issues/660.
=> chore: update adal deps to v0.9.18

Makefile
=> chore: bump version to v1.0.1 in release-1.0

pkg/provider/provider.go, pkg/provider/provider_test.go, pkg/server/server.go
=> refactor: use secret file for object versions

manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/templates/_helpers.tpl, manifest_staging/charts/csi-secrets-store-provider-azure/values.yaml
Signed-off-by: Nick Fisher <nxf5025@gmail.com>
The fullnameOverride is documented in the README.md, but is not implemented as part of the helm chart helpers.
=> fix: Add missing fullnameOverride to helm chart

docs/keyvault-test-setup.md
- Adds instructions for keyvault setup and commands used to generate the test secret/key/certs
=> docs: add keyvault artificats setup for testing

.github/workflows/website.yaml, website/config.toml
part of #615 
- Updates gh workflow to publish the docs to `docs` directory in gh-pages
Validated here: https://aramase.github.io/secrets-store-csi-driver-provider-azure
=> chore: update website deploy workflow

Makefile, charts/csi-secrets-store-provider-azure/README.md, examples/kind/kind-demo.sh, manifest_staging/charts/csi-secrets-store-provider-azure/README.md, website/content/en/configurations/deploy-in-openshift.md, website/content/en/configurations/ingress-tls.md, website/content/en/demos/standard-walkthrough/_index.md, website/content/en/getting-started/installation/_index.md
part of #615 
- The helm charts have been moved to `https://azure.github.io/secrets-store-csi-driver-provider-azure/charts`. With this PR, we're updating the install instructions to use the new helm chart repository URL.
=> docs: update chart repo to `https://azure.github.io/secrets-store-csi-driver-provider-azure/charts`

Makefile, examples/kind/kind-demo.sh
- `shellcheck */*.sh` doesn't check all the shell files in the repo. Changing to use `find` all files and then run shellcheck.
- Fixes errors
=> ci: fix shellcheck file paths

.github/workflows/create-release.yaml, .goreleaser.yml
- Use goreleaser for generating changelog when a new tag is published
fixes #68 
Testing in my fork:
- https://github.com/aramase/secrets-store-csi-driver-provider-azure/releases/tag/v1.1.0
=> ci: add goreleaser workflow for release

.pipelines/templates/aks-setup.yaml, .pipelines/templates/build-images.yaml
=> test: fix upgrade tests

pkg/auth/auth.go, test/e2e/framework/deploy/deploy.go, test/e2e/workload_identity_test.go
- Enables workload identity test with driver and provider deploy manifests
=> test: enable workload identity test with deploy manifests

test/e2e/workload_identity_test.go
- Enabling workload identity with soak clusters
- Updated the soak clusters with `--enable-oidc-issuer`.
- Setup federated identity credential with the issuer and <service account name, namespace>
=> test: enable workload identity test with soak clusters 

.github/dependabot.yml, azure-pipelines.yml
=> ci: use chore prefix for dependabot updates and update pr exclude paths

.devcontainer/Dockerfile
Updated versions:
- golang base container updated to 1.17
- jq updated to 1.6
- helm updated to 3.7.0
- kind updated to 0.12.0
- kubectl updated to 1.22.2
This also removes a few packages that were installed and are currently marked as deprecated where the replacements are packages we're already installing:
- gocode/gocod-mod is superseeded by gopls
- gometalinter is superseeded by golangci-lint
Additionally, golangci-lint is now installed via go install instead of curl-ing then sourcing the install script
When working on #834 I ran into some issues because the devcontainer was configured to use an older version of go than this project currently requires.
**If …
=> fix: update versions installed in devcontainer

.pipelines/templates/role-assignment.yaml, Makefile
Switching staging registry from using upstreamk8sci to upstream.
=> chore: switch to upstream acr

test/e2e/framework/deploy/deploy.go, test/e2e/framework/helm/helm.go
=> test: set -v=5 to get debug logs in e2e

.pipelines/templates/e2e-test-kind.yaml, Makefile, website/content/en/_index.md
- Update kind to `v0.12.0`
- Remove Kubernetes version 1.20 from docs and CI since it has reached EOL
- Update Kubernetes versions to latest in CI for supported releases
=> ci: remove kubernetes version 1.20 (EOL)

website/content/en/configurations/identity-access-modes/pod-identity-mode.md
In docs, in point 7 there is a typo usepodidentity should be usePodIdentity.
Fixes #866 
Just a documentation change.
=> docs: Update pod-identity-mode.md

pkg/provider/provider.go, pkg/provider/provider_test.go, pkg/provider/types/constants.go, pkg/provider/types/parameters.go, pkg/provider/types/parameters_test.go, pkg/provider/types/types.go, test/e2e/auto_rotation_test.go, test/e2e/certificates_test.go, test/e2e/custom_cloudenv_test.go, test/e2e/key_test.go, test/e2e/pod_identity_test.go, test/e2e/secret_file_permission_test.go, test/e2e/secret_test.go, test/e2e/user_assigned_identity_test.go, test/e2e/workload_identity_test.go
- Adds functions to get parameters from the attributes map
- Adds unit tests to validate the get parameters functions
- Makes the parameter names constant, so it can be reused in code and tests
=> refactor: add functions to get parameters and add constants

test/e2e/go.mod, test/e2e/go.sum
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/security/dependabot/4 by upgrading github.com/opencontainers/runc to v1.1.2
=> security: fix CVE-2022-29162

pkg/provider/types/parameters.go, pkg/provider/types/parameters_test.go, pkg/provider/types/types.go
- Changes the tenant id parameter to `tenantID` from `tenantId` to be consistent with the naming convention.
- This change is backward compatible as we fallback on `tenantId` in case `tenantID` is not set.
- The `TenantIDParameter` constant can be changed to `tenantID` after 1.2 release as it's used in upgrade tests.
- We'll need to keep the old `tenantId` parameter a couple of releases before we completely remove it.
- The log is set at level 3 instead of warning, as warning can be too verbose and logged every time the we get a mount request.
fixes #857 
**If "Yes," did you notify that project's …
=> fix: use `tenantID` instead of `tenantId` in parameters

test/e2e/auto_rotation_test.go, test/e2e/pod_identity_test.go
Fixes failures in arc nightly test runs: https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=45173&view=logs&jobId=51811eea-cde0-5499-71d2-3da72322665f
- Skips pod identity tests for arc testing
=> test: skip pod identity tests for arc

arc/conformance/plugin/Dockerfile
- Update debian-base to bullseye-v1.3.0
=> chore: update debian-base to bullseye-v1.3.0

website/content/en/getting-started/usage/_index.md
Updated the doc to include the link and an example for workload identity.
It's hard to find the right configuration for workload identity use case.
No.
I was trying to set up the integration with workload identity in AKS, and found out it's hard to see find the example from here. I hope this update can help others too.
=> docs: updated the document to include workload identity

CODEOWNERS
=> ci: add CODEOWNERS file

pkg/provider/provider.go, pkg/provider/provider_test.go
- Adds a warning log when the number of certs after reconstructing certificate chain is not equal to the number of certs from key vault.
- This can be caused when the chain is incomplete
fixes #879 
=> chore: add additional logs in fetch cert chain

arc/conformance/plugin/arc_conformance.sh, test/e2e/e2e_suite_test.go
```bash
Failed to create JUnit report file: /mnt/vss/_work/1/s/test/e2e
open /mnt/vss/_work/1/s/test/e2e: is a directory
Failed to generate JUnit report data:
invalid argument
```
- Adds a filename for the junit report to be used by the reporter. 
- It fails now because `JUNIT_OUTPUT_FILEPATH` is a directory
=> test: fix junit reporter filename

arc/conformance/plugin/Dockerfile
- update debian-base to bullseye-v1.4.0
=> chore: update debian-base to bullseye-v1.4.0

go.mod, go.sum, test/e2e/go.mod, test/e2e/go.sum, tools/go.mod, tools/go.sum
Fixes CVE-2022-29526 - https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=51084&view=logs&jobId=50e5c204-a982-5a63-4824-cf22f1b24a4e&j=50e5c204-a982-5a63-4824-cf22f1b24a4e&t=795dd060-7255-5745-ea64-907869e3f465
=> security: fix CVE-2022-29526

.pipelines/templates/e2e-test-kind.yaml
- Remove Kubernetes version 1.21 from CI since it has reached EOL
- Update Kubernetes versions to latest in CI for supported releases
=> ci: remove kubernetes version 1.21 (EOL)

arc/portal_gallery_package/DeploymentTemplates/DefaultTemplate.json
The Azure Portal Gallery deployment for Arc is missing the SystemAssigned identity causing missing rolebindings on the cluster. 
Fixes #948
Co-author: @eliises
=> fix bug #948 arc missing system identity

test/e2e/go.mod, test/e2e/go.sum
ref: https://github.com/advisories/GHSA-r48q-9g5r-8q2h
=> security: fix CVE-2022-1996

.pipelines/templates/e2e-test-kind.yaml
- The e2e pipeline has been flaky and fails during `kind create cluster`. This could be a bug with the older kubernetes version, so bumping to latest available images.
xref: https://github.com/kubernetes-sigs/kind/issues/2942
=> chore: bump k8s versions for kind tests

.pipelines/templates/e2e-test-kind.yaml
- Remove Kubernetes version 1.22 from docs and CI since it has reached EOL
- Update Kubernetes versions to latest in CI for supported releases
=> ci: remove kubernetes version 1.22 (EOL)

.github/dependabot.yml
=> chore: enables docker ecosystem for dependabot

website/content/en/getting-started/usage/_index.md
Signed-off-by: Javier Vela <fjvela@gmail.com>
**Reason for Change**: Fix a 404 error link to Workload Identity config page
=> docs: fix workload identity link

.pipelines/templates/e2e-test-kind.yaml
- enable tests with kubernetes v1.26
=> ci: enable tests with kubernetes v1.26

.pipelines/templates/e2e-test.yaml, test/e2e/e2e_suite_test.go, test/e2e/framework/helm/helm.go
- update helm install logic for upgrade tests
- we can't use `charts/csi-secrets-store-provider-azure` when cutting releases because the image will be latest and not yet available. So switching the logic to use the official helm chart repo to install the latest available provider.
=> test: update helm install logic for upgrade tests

.pipelines/templates/cleanup-images.yaml, Makefile
- Remove `1903`, `1909` and `2004` for windows builds (EOL)
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1903-end-of-servicing
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-1909-end-of-servicing
- https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-version-2004-end-of-servicing
=> chore: remove windows version 1903, 1909 and 2004 (EOL)

examples/kind/README.md, website/content/en/configurations/custom-environments.md, website/content/en/configurations/identity-access-modes/pod-identity-mode.md, website/content/en/configurations/identity-access-modes/service-principal-mode.md, website/content/en/configurations/identity-access-modes/system-assigned-msi-mode.md, website/content/en/configurations/identity-access-modes/user-assigned-msi-mode.md, website/content/en/configurations/identity-access-modes/workload-identity-mode.md, website/content/en/configurations/ingress-tls.md, website/content/en/configurations/set-env-var.md, website/content/en/configurations/sync-multiple-versions.md, website/content/en/configurations/sync-with-k8s-secrets.md, website/content/en/demos/standard-walkthrough/_index.md, website/content/en/getting-started/usage/_index.md
tenantId param will be deprecated in favor of tenantID. update the documentation to reflect change from 'tenantId' to 'tenantID
fixes https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/1027
=> docs: Update documentation to reflect change from 'tenantId' to 'tenantID'

Makefile
- pin buildx to `v0.10.6`
- pinning buildkit version to v0.10.6 as v0.11.0 is injecting sbom/prov to manifest causing the manifest push to fail
=> chore: pin buildx to `v0.10.6`

.pipelines/templates/arc/setup.yaml
- The PR gate and nightly test runs for arc are failing due to issues with the latest `k8s-extension`. Pinning to a specific version of the extension that works!
Test run with pinning the version: https://dev.azure.com/AzureContainerUpstream/Secrets%20Store%20CSI%20Driver%20Provider%20Azure/_build/results?buildId=77487&view=results
fixes #1076 
=> ci: pin k8s-extension version to `1.3.5`

docs/sample/ingress-controller-tls/deployment-app-one.yaml, docs/sample/ingress-controller-tls/deployment-app-two.yaml, examples/pod-identity/pod-inline-volume-pod-identity.yaml, examples/service-principal/pod-inline-volume-service-principal.yaml, examples/sync-as-kubernetes-secret/deployment-synck8s.yaml, examples/system-assigned-managed-identity/pod-inline-volume-system-assigned-identity.yaml, examples/user-assigned-managed-identity/pod-inline-volume-user-assigned-identity.yaml, test/e2e/framework/pod/pod.go, website/content/en/configurations/identity-access-modes/pod-identity-mode.md, website/content/en/configurations/identity-access-modes/service-principal-mode.md, website/content/en/configurations/identity-access-modes/system-assigned-msi-mode.md, website/content/en/configurations/identity-access-modes/user-assigned-msi-mode.md, website/content/en/configurations/identity-access-modes/workload-identity-mode.md, website/content/en/configurations/set-env-var.md, website/content/en/configurations/sync-multiple-versions.md, website/content/en/configurations/sync-with-k8s-secrets.md, website/content/en/demos/standard-walkthrough/_index.md
- use `registry.k8s.io/e2e-test-images/busybox:1.29-4` for e2e
- `k8s.gcr.io/e2e-test-images/busybox:1.29` doesn't work with Windows 2022
=> test: use `registry.k8s.io/e2e-test-images/busybox:1.29-4` for e2e

arc/conformance/plugin/Dockerfile, test/load/deployment-template.yaml
- use base and test image from `registry.k8s.io`
=> chore: use base and test image from `registry.k8s.io`

.pipelines/templates/e2e-test-kind.yaml
- remove kubernetes version 1.23 (EOL)
=> docs: remove kubernetes version 1.23 (EOL)

manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
The Fluentd container is crashing on one of the customer's OpenShift clusters. Based on customer feedback, I am updating the resource values. I have manually tested this change on the ARO cluster.
=> chore: updates Arc monitoring resources

README.md, website/content/en/_index.md
**Issue Fixed**: 
Fixes  #1095 
=> docs: adds links and support statement for managed offerings

.pipelines/templates/arc/extension-create.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
Updates MSI Adapter to address vulnerability fixes.
=> chore: updates msi-adapter image

manifest_staging/charts/csi-secrets-store-provider-azure/arc-values.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer-windows.yaml
This PR adds outbound proxy env variable support for windows pod
=> feat: adds outbound proxy env variable support for windows pod

arc/conformance/plugin/Dockerfile, test/load/deployment-template.yaml
Cherry pick of #1082 on release-1.4.
#1082: chore: use base and test image from `registry.k8s.io`
=> Automated cherry pick of #1082: chore: use base and test image from `registry.k8s.io`

.devcontainer/Dockerfile, .github/workflows/cover.yaml, .golangci.yml
=> chore: update to go 1.20

.devcontainer/Dockerfile, .pipelines/templates/e2e-test-azure.yaml, .pipelines/templates/soak-test.yaml, Makefile, arc/conformance/plugin/Dockerfile
The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
xref: https://github.com/kubernetes/k8s.io/issues/2396
=> chore: use `dl.k8s.io` instead of hardcoded url

.pipelines/templates/e2e-test-azure.yaml, .pipelines/templates/soak-test.yaml
Add `-L` flag to the curl command to follow redirect while getting the latest stable version for kubectl.
```bash
➜ curl -s https://dl.k8s.io/release/stable.txt
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
➜ curl -sL https://dl.k8s.io/release/stable.txt
v1.27.2
```
=> ci: fix kubectl download url

.pipelines/templates/aks-setup.yaml
The AKS LIST versions has API in azure-cli has been updated to latest and breaks compatibility. It no longer has `orchestrators[*].orchestratorVersion`. Refer to https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?tabs=HTTP#kubernetesversionlistresult for sample result.
=> ci: fix `az aks get-versions` command failure

manifest_staging/charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml
This change fixes an issue with `genevafluentd_td_agent:mariner_20230915.3`:
This image appears to use an updated version of `fluentd` where the `FLUENTD_CONF` is no longer supported. Instead, the environment variable is now [`FLUENT_CONF`](https://docs.fluentd.org/configuration/config-file#fluent_conf-environment-variable).
With this change, fluentd is able to find the `fluentd.conf` file:
=> fix: update fluentd env var with new env var name

go.mod, go.sum, test/e2e/go.mod, test/e2e/go.sum, tools/go.mod, tools/go.sum
Bump google.golang.org/protobuf@v1.33.0 and github.com/golang/protobuf@v1.5.4 to address https://github.com/advisories/GHSA-8r3f-844c-mc37.
https://pkg.go.dev/vuln/GO-2024-2611
https://github.com/advisories/GHSA-8r3f-844c-mc37
=> security: CVE-2024-24786: bump google.golang.org/protobuf to v1.33.0

.pipelines/templates/scan-images.yaml
=> chore: bump trivy to 0.50.1

go.mod, go.sum, test/e2e/go.mod, test/e2e/go.sum
- bump golang.org/x/net to v0.23.0+ to fix [GO-2024-2687](https://pkg.go.dev/vuln/GO-2024-2687)
=> chore: bump golang.org/x/net from 0.17.0 to 0.24.0

.github/workflows/scorecards.yml
Updating `ossf/scorecard-action` to latest (v2.3.1) to resolves [failures](https://github.com/Azure/secrets-store-csi-driver-provider-azure/actions/runs/8696368466/job/23849474524).
xref: https://github.com/ossf/scorecard-action/issues/997
=> ci: bump ossf/scorecard-action to v2.3.1

pkg/provider/provider.go, pkg/provider/provider_test.go
This PR fixes #1257 where the fetchCertChain function is unable to resolve the leaf certificate when sorting the chain. This is caused by the leaf certificate missing the optional SubjectKeyIdentifier extension, therefore getting matched as the parent to the CA certificate.
#1257
I work for Microsoft, alias: chriscur
=> fix: cert chain sorting when the leaf certificate is missing the SubjectKeyIdentifier extension

pkg/provider/provider.go, pkg/provider/provider_test.go
Cherry pick of #1509 on release-1.5.
#1509: Handles the case where the optional leaf SKI is missing
=> fix: Handles the case where the optional leaf SKI is missing

.pipelines/e2e-job-azure.yaml, .pipelines/templates/aks-setup.yaml, .pipelines/templates/e2e-test-azure.yaml
- The default container runtime is `containerd` in windows, so the `windows_containerd` job was a duplicate with steps that weren't required.
=> ci: cleanup windows pr gate

manifest_staging/charts/csi-secrets-store-provider-azure/config/telegraf-conf.tmpl
Telegraf sidecar in `akvsecretsprovider-arc-monitoring` pod is crashing upon startup because `telegraf.conf` uses deprecated option `response_timeout`.
=> fix: telegraf response_timeout to timeout

charts/csi-secrets-store-provider-azure/Chart.yaml, charts/csi-secrets-store-provider-azure/arc-values.yaml, charts/csi-secrets-store-provider-azure/config/telegraf-conf.tmpl, charts/csi-secrets-store-provider-azure/templates/arc-monitoring.yaml, manifest_staging/charts/csi-secrets-store-provider-azure/Chart.yaml
=> chore: v1.5.6 chart release to disable arc monitoring by default

cmd/main.go, go.mod, go.sum, pkg/auth/auth.go, test/e2e/go.mod, test/e2e/go.sum
Cherry pick of #1611 on release-1.5.
#1611: chore: remove direct dependency on adal
=> chore: remove direct dependency on adal

.pipelines/templates/aks-setup.yaml
fixes nightly CI failures
```bash
ERROR: (K8sVersionNotSupported) Managed cluster sscd-e2e-ec52ce9341f2 is on version 1.27.1, which is only available for Long-Term Support (LTS). If you intend to onboard to LTS, please ensure the cluster is in Premium tier and LTS support plan (see https://aka.ms/aks/enable-lts). Otherwise, use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list
Code: K8sVersionNotSupported
```
=> ci: update `az aks get-versions` command query

.github/workflows/scorecards.yml
Scorecards action run is failing because `v3` of `actions/upload-artifact` is deprecated. Bumping it to `v4`.
ref: https://github.com/Azure/secrets-store-csi-driver-provider-azure/actions/runs/14138326613/job/39615056456
=> ci: update actions/upload-artifact to v4

.pipelines/templates/aks-setup.yaml
```bash
➜ az aks get-versions -l southcentralus -o json | jq -r '
.values[]
| select(.capabilities.supportPlan | index("AKSLongTermSupport") | not)
| .patchVersions
| to_entries[]
| .key
' | sort -V | head -n 1
1.29.0
➜ az aks get-versions -l southcentralus -o json | jq -r '
.values[]
| select(.capabilities.supportPlan | index("AKSLongTermSupport") | not)
| .patchVersions
| to_entries[]
| .key
' | sort -V | tail -n 1
1.32.3
```
=> ci: update `az aks get-versions` command query to get min/max versions

.github/workflows/chart.yaml, .github/workflows/create-release.yaml, .github/workflows/scan-vulns.yaml, .github/workflows/website.yaml
Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101.
=> ci: use ubuntu-latest for gh workflows

.pipelines/templates/e2e-test-azure.yaml, .pipelines/templates/e2e-test-kind.yaml, .pipelines/templates/unit-test.yaml, go.mod, test/e2e/go.mod, tools/go.mod
Cherry pick of #1921 on release-1.7.
#1921: Bump Go version to 1.24.6
=> chore: update to go 1.24.6
